name: Report Automation

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 16 * * *'  # Runs at 4:00 PM UTC (6:00 PM Egypt time) every day
    - cron: '0 23 * * *'  # Runs at 11:00 PM UTC (1:00 AM Egypt time) every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymongo pytz  # Include 'pytz' for timezone handling

      - name: Run Python script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
        run: |
          python bedoReport.py  # Replace with the relative path to your script in the repository